/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
*/

function findTheDifference(s, t){
    s = s.split("").sort().join("");
    t = t.split("").sort().join("");
    for(let i = 0; i < t.length; i++){
        if(s[i] !== t[i]){
            return t[i];
        }
    }
}

let s1 = "abcd";
let s2 = "";
let t1 = "abcde";
let t2 = "y";

console.log(findTheDifference(s1, t1));
console.log(findTheDifference(s2, t2));